### ISSUE TITLE
DXM + MXE: Low Risk & No Synergy -> Low Risk & Synergy / Caution / Unsafe / Dangerous (?)

### ISSUE THREAD

**Issue by konrad-komisarczyk** [TripSit/drugs#29]
I think we should modify <drug> so that <change you want to make>.

Same case with synergy as DXM + Ketamine (both substances exert their effects mainly via NMDA antagonism). 

There may be also possible serotonin syndrome, as DXM is known to cause serotonin syndrome in combination with other serotonin reuptake inhibitors and there is research suggesting that MXE displays significant affinity towards the serotonin transporter, sources: 
* [https://doi.org/10.1371/journal.pone.0059334](https://doi.org/10.1371/journal.pone.0059334)
* [https://www.sciencedirect.com/science/article/abs/pii/S0014488621002442](https://www.sciencedirect.com/science/article/abs/pii/S0014488621002442)

If the suspicion about serotonin syndrome is true, then I don't know which of "unsafe" categories should it be marked? Probably "Unsafe"?

Other MXE interactions also need reviewing.

**Comment by LunaUrsa** [comment]
Thoughts on this one @utaninja ?

**Comment by utaninja** [comment]
It seems there is a conflict on if there is a concern with MXE and serotonin syndrome. An example of this is Psychonaut Wiki/TripSit's interaction with MDMA + MXE "There have been reports of concerning serotonergic interactions when the two are taken at the same time, but MXE taken to the end of an MDMA experience does not appear to cause the same issues." or SSRI + MXE "Depending on the SSRI this combination can be unpredictable" (although I'm not sure exactly what this means)

I have been unable to find a single case of MXE and serotonin syndrome. I do not know enough about this topic to give an opinion on it. Throughout various scattered internet discussions, many people are proposing that it doesn't have a high enough affinity to be of concern for an interaction.

[https://bluelight.org/xf/threads/suspected-serotonin-syndrome-from-methoxetamine-use.563915/)
https://pdsp.unc.edu/databases/pdsp.php?](https://bluelight.org/xf/threads/suspected-serotonin-syndrome-from-methoxetamine-use.563915/)receptorDD=&receptor=&speciesDD=&species=&sourcesDD=&source=&hotLigandDD=&hotLigand=&testLigandDD=&testFreeRadio=testFreeRadio&testLigand=methoxetamine&referenceDD=&reference=&KiGreater=&KiLess=&kiAllRadio=all&doQuery=Submit+Query

I think this should be looked at in-depth and cross-checked before being pushed.

**Comment by utaninja** [comment]
From discord user RedDefault- 
My own opinion on the matter - At least in regards to SS - 
"DXM+MXE= Caution to unsafe (both have appreciable SERT activity, no reported cases or studies, but inference does lend to concern and better safe than sorry)"

**Comment by utaninja** [comment]
Forwarding comments from a user on discord here:
Regarding the discussion on MXE+DXM and SS concerns, this will be a bit lengthy. 

Both DXM and MXE have (similar) high affinity for SERT, but little to no affinity for 5-HTs (although MXE is less comprehensive, but at least 5-HT2 has been looked at) [1,2,3,4]. This does raise the concern of course for SS (e.g. MDMA and SSRIs), however I could not find anything explicitly looking at MXE and SSRIs. So we can try to compare to similar systems. 

Looking at DXM and SSRIs, it can be observed there are reports of dangerous combinations [5,6]. However, is this from the pure DXM+SSRI interaction on SERT? I don't think the pharmacological profile tells the whole story, rather I suspect this is a metabolism issue. Some SSRIs do inhibit CYP2D6, the main enzyme for inactivating DXM, so the concentration and effect of DXM is far higher than typical. Furthermore, all reported clinical cases are of DXM+an SSRI that does inhibit CYP2D6. And this only appears to occur at very high DXM doses (i.e. the lower dose range of DXM may be fine). As the authors state, the high use of DXM containing products with SSRIs would mean there should be a lot of reported cases, but as stated, there aren't. The only ones that are reported are high doses of DXM with SSRIs that inhibit DXM metabolism. So regarding DXM and SSRIs, combinations can be dangerous, but I think this highly depends on the type of SSRI and the dose of DXM. But better safe than sorry and a chart can't hold naunce, so I think it should remain dangerous, but these references should be added, and an actual discussion on DXM metabolism and dosing and why/how SS can occur with what types of SSRIs (not all SSRIs metabolize CYP2D6). 

Now while there is no data on MXE and SSRIs, there is evidence on ketamine and SSRIs. I disagree with the statements of the authors on ketamine affinity to SERT in the ones cited in the MXE+DXM section. Ketamine does have affinity to SERT, albeit significantly lower than MXE (100x diff) [7].


Ketamine with SSRIs have been extensively looked at, and have been shown to be safe [8,9,10,11]. Ketamine metabolism is different from DXM, and thus SSRIs don't have the same negative effect as with DXM. Although inhibition of ketamine metabolism via other means such as grapefruit can potentially be problematic [12]. I don't know why Ketamine+SSRIs don't have any sources, but you can include the sources I've put if you'd like (better than nothing). 

So now comparing ketamine with MXE. There are quite a number of differences that prevent the comparison of the safety profile of ket to MXE. MXE has much higher affinity than ketamine to SERT, and whereas ketamine is rapidly metabolized, MXE is not resulting in much higher concentrations of MXE than ketamine [13]. However, the metabolic pathway is similar, so SSRIs and subsequently DXM should not have any cross interference. The problem here though is, is DXM effect on SERT enough to cause SS when compounded with other compounds that do the same? The comparison to DXM+SSRIs cannot be made due to metabolism complications. I have attempted to look at other compounds with similar SERT affinity (e.g. MDMA) but these are also complicated by affinity to 5-HT receptors. I do not think any inference can therefore be made on MXE+SSRI or MXE+DXM for these reasons. Therefore, I would state that MXE+SSRI and MXE+DXM should have the exact same rating. While SS has not been shown, the affinities are high enough that I do think the potential for complications are there depending on dosing. As such, I would state both MXE+DXM and MXE+SSRI should be under caution (I for one would err on the safe side and put unsafe, but at minimum I would put caution).

1. https://www.sciencedirect.com/science/article/pii/S0028390817301855
2. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3602154/
3. https://www.sciencedirect.com/science/article/pii/S0014488607002543
4. https://www.sciencedirect.com/science/article/pii/S0163725816000176
5. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5747823/
6. https://www.tandfonline.com/doi/full/10.1080/15563650701668625
7. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6020109/
8. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8538895/
9. https://www.cambridge.org/core/journals/psychological-medicine/article/abs/single-iv-ketamine-augmentation-of-newly-initiated-escitalopram-for-major-depression-results-from-a-randomized-placebocontrolled-4week-study/306D6680A053D46D05314224AF52496B
10. https://www.tandfonline.com/doi/full/10.1080/14656566.2019.1683161
11. https://academic.oup.com/ijnp/article/22/10/616/5530582?login=false
12. https://www.psychiatrist.com/jcp/ketamine-for-depression-pharmacokinetic-and-pharmacodynamic-drug-interactions/
13. https://linkinghub.elsevier.com/retrieve/pii/S0361-9230(16)30098-3

**Comment by utaninja** [comment]
This has been accepted and can be found here- https://github.com/TripSit/drugs/pull/47
