### ISSUE TITLE
Cocaine + Alcohol

### ISSUE THREAD

**Issue by utaninja** [TripSit/drugs#98]
### Discussed in https://github.com/TripSit/drugs/discussions/74

<div type='discussions-op-text'>

<sup>Originally posted by **zelixir25** February 26, 2024</sup>
Just adding some sources for this combination. It's quite a popular one so I think having some sources highlighting the risks might be helpful.

I would also update the text to "The combination of cocaine and alcohol produces cocaethylene as a metabolite, which may be more cardiotoxic than cocaine or alcohol alone. Some studies indicate that cocaine + alcohol is more dangerous than either drug on its own. Use caution if combining these substances."

Sources:
McCance-Katz, E. F., Kosten, T. R., & Jatlow, P. (1998). Concurrent use of cocaine and alcohol is more potent and potentially more toxic than use of either alone—A multiple-dose study. Biological Psychiatry, 44(4), 250–259. https://doi.org/10.1016/S0006-3223(97)00426-5

Pergolizzi, J., Breve, F., Magnusson, P., LeQuang, J. A. K., & Varrassi, G. (2022). Cocaethylene: When cocaine and alcohol are taken together. Cureus, 14(2), e22498. https://doi.org/10.7759/cureus.22498

Shastry, S., Manoochehri, O., Richardson, L. D., & Manini, A. F. (2023). Cocaethylene cardiotoxicity in emergency department patients with acute drug overdose. Academic Emergency Medicine, 30(2), 82–88. https://doi.org/10.1111/acem.14584

Wiener, S. E., Sutijono, D., Moon, C. H., Subramanian, R. A., Calaycay, J., Rushbrook, J. I., & Zehtabchi, S. (2010). Patients with detectable cocaethylene are more likely to require intensive care unit admission after trauma. The American Journal of Emergency Medicine, 28(9), 1051–1055. https://doi.org/10.1016/j.ajem.2009.06.014

@zelixir25 on discord:
"one combo i would want to talk about the classification for is cocaine + alcohol. the research seems fairly inconclusive about cocaethylene's cardiotoxicity. some studies say it's more cardiotoxic while others don't. given the disagreement i would honestly push for reclassifying it as caution rather than unsafe.
the risk, afaict, is that both substances can inhibit some effects of the other which causes people to use more which results in greater risks rather than cocaethylene specifically causing more issues"
</div>

Studies indicate that this combination is more dangerous than either drug on its own. Because cocaine can decrease some of the intoxicating effects of alcohol, some people may drink more than they otherwise would, leading to greater behavioral and physical health risks. Moreover, there is still some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own.

Unsafe

**Comment by zelixir25** [comment]
so we're classifying this as unsafe?

**Comment by utaninja** [comment]
> so we're classifying this as unsafe?

Yeah, unless noted otherwise sources in issues are for just source additions.

**Comment by zelixir25** [comment]
okay I disagree with that. I think it should be caution. I mean...we say "use caution" in the updated description for it unless we're ignoring that proposal in my update as well. I don't think there's enough evidence to categorically say it's unsafe. I think it's similar to alcohol + other stimulants: the inhibitory effects can lead to using higher amounts which increases risk above baseline.

I think if our explanation should be "Studies indicate that this combination is may be more dangerous than either drug on its own. Because cocaine can decrease some of the intoxicating effects of alcohol, some people may drink more than they otherwise would, leading to greater behavioral and physical health risks. Moreover, there is still some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use caution when combining these substances."

**Comment by utaninja** [comment]
Just to clarify, I was saying that due to your suggestion being a source addition, I did not assume you wanted the interaction label to be changed unless if stated.

So if I make a post for  GHB/GBL + Alcohol and add a source, unless if I also state I want it to change to caution, then it's assumed to stick with dangerous as it currently is.

For your comment on the interaction modification, to clarify you are saying to add "Use caution when combining these substances."?
I did not ignore that part of the proposal, it simply seemed extra to me if it was already labeled as unsafe.

However, if this was to be changed to:

Cocaine + Alcohol = Caution
"Studies indicate that this combination is may be more dangerous than either drug on its own. Because cocaine can decrease some of the intoxicating effects of alcohol, some people may drink more than they otherwise would, leading to greater behavioral and physical health risks. Moreover, there is still some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use caution when combining these substances."

Would you still want the line "Use caution when combining these substances." are the end? As if this is the label for the interaction I think that would be enough to demonstrate it. Either works though.

**Comment by zelixir25** [comment]
good question. maybe "Use moderation when combining these substances." is better! you're right it's a bit redundant otherwise.

so in full (reworded some things a bit to make it more clear):
Because cocaine can decrease some of the intoxicating effects of alcohol, some people may drink more than they otherwise would, leading to greater behavioral and physical health risks. Moreover, there is still some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use moderation when combining these substances

**Comment by utaninja** [comment]
Looks good to me. Perhaps Cocaine can decrease some of the intoxiciating effects of alcohol, due to this some people.. etc?

**Comment by zelixir25** [comment]
Cocaine can decrease some of the intoxicating effects of alcohol, causing some people to drink more than they otherwise would, which leads to greater behavioral and physical health risks. There is also some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use moderation when combining these substances.

**Comment by utaninja** [comment]
Final:
Cocaine + Alcohol = Caution

Cocaine can decrease some of the intoxicating effects of alcohol, causing some people to drink more than they otherwise would, which leads to greater behavioral and physical health risks. There is also some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use moderation when combining these substances.
